-- Staff registry sync (generated by scripts/gen-staff-sync.mjs — do not hand-edit)
-- Source: timetable/dott-baseline.json built 2026-08-06
-- Safe to re-run after every timetable change: upserts on hub_key, never deletes.

alter table public.staff add column if not exists hub_key text unique;

insert into public.staff (full_name, staff_type, fte, hub_key, notes) values
  ('John Dunbar', 'classroom', 1.00, 'LA6', 'Classroom · LA6 (5/6)'),
  ('Nicola Pigott', 'classroom', 1.00, 'LA7', 'Classroom · LA7 (5)'),
  ('Janette Crisp', 'classroom', 1.00, 'LA8', 'Classroom · LA8 (6)'),
  ('Lincoln Rose', 'classroom', 1.00, 'LA9', 'Classroom · LA9 (5/6)'),
  ('Olivia Sheehy', 'classroom', 1.00, 'LA14', 'Classroom · LA14 (3/4)'),
  ('Georgia Mitchell', 'classroom', 1.00, 'LA15', 'Classroom · LA15 (3)'),
  ('Tanya Thieme', 'classroom', 1.00, 'LA16', 'Classroom · LA16 (4)'),
  ('Cassidy Law', 'classroom', 1.00, 'LA17', 'Classroom · LA17 (4/5)'),
  ('Hannah Bouwmeester', 'classroom', 1.00, 'LA18', 'Classroom · LA18 (2)'),
  ('Savannah Espach', 'classroom', 1.00, 'LA19', 'Classroom · LA19 (2)'),
  ('Anna Hendron', 'classroom', 1.00, 'LA20', 'Classroom · LA20 (2)'),
  ('Jasper Sirr-Davis', 'classroom', 1.00, 'LA21', 'Classroom · LA21 (3)'),
  ('Imogen Webb', 'classroom', 1.00, 'LA22', 'Classroom · LA22 (1)'),
  ('Ashlee Hutchings', 'classroom', 1.00, 'LA23', 'Classroom · LA23 (1)'),
  ('Chloe Moore', 'classroom', 1.00, 'LA24', 'Classroom · LA24 (1)'),
  ('Chantel Uhe', 'specialist', 0.40, 'spec:Uhe', 'Specialist · works Tue/Wed'),
  ('Lis Lowndes', 'specialist', 1.00, 'spec:Lowndes', 'Specialist · works Mon/Tue/Wed/Thu/Fri'),
  ('Natalie Carter', 'specialist', 0.60, 'spec:Carter', 'Specialist · works Mon/Tue/Wed'),
  ('Cheryl Peak', 'specialist', 0.80, 'spec:Peak', 'Specialist · works Tue/Wed/Thu/Fri'),
  ('Rachel Walker', 'specialist', 0.40, 'spec:Walker', 'Specialist · works Wed/Thu'),
  ('Aaron Bell', 'specialist', 0.40, 'spec:Bell', 'Specialist · works Thu/Fri'),
  ('Jake Pevitt', 'specialist', 0.20, 'spec:TBC', 'Specialist · works Thu'),
  ('Jenny Martin', 'classroom', 1.00, 'ece:Jenny Martin', 'PP · LA5'),
  ('Caroline Parkin', 'classroom', 1.00, 'ece:Caroline Parkin', 'PP · LA2'),
  ('Katie Digney', 'classroom', 0.80, 'ece:Katie Digney', 'PP · LA1'),
  ('Nikki Luca', 'classroom', 0.40, 'ece:Nikki Luca', 'PP · LA1'),
  ('Kelly Duggan', 'classroom', 0.80, 'ece:Kelly Duggan', 'Kindy · LA4'),
  ('Donna Campbell', 'classroom', 0.80, 'ece:Donna Campbell', 'Kindy · T10'),
  ('Fiona Dyer', 'classroom', 0.60, 'ece:Fiona Dyer', 'Kindy · T9'),
  ('Anita Currion', 'classroom', 0.80, 'ece:Anita Currion', 'Kindy · LA3')
on conflict (hub_key) do update set
  full_name  = excluded.full_name,
  staff_type = excluded.staff_type,
  fte        = excluded.fte,
  notes      = excluded.notes,
  active     = true,
  updated_at = now();
